# Chap1 - Tensorflow 101

## Covered
- What is tensorflow ?
- 3 Models that make up tf ?
- `Session()` vs `InteractiveSession()`
- What is a tensor ?
- Syntax for:
    - constant
    - operation
    - placeholder
    - Variable
- placeholder vs variable
- How do you provide placeholder values when running ?
- `tf.convert_to_tensor()`
- How do you initialize variables ?

## Notes

### What is TF? 
TensorFlow is an open source library for numerical computation using data flow graphs.

### 3 Parts to tf
- Data model comprises of tensors, that are the basic data units created,
manipulated, and saved in a TensorFlow program.
- Programming model comprises of data flow graphs or computation graphs.
Creating a program in TensorFlow means building one or more TensorFlow
computation graphs.
- Execution model consists of firing the nodes of a computation graph in a
sequence of dependence. The execution starts by running the nodes that are
directly connected to inputs and only depend on inputs being present.

### TensorFlow Core (9-24)
TensorFlow core is the lower level library on which the higher level TensorFlow modules are built.

#### Hello World

In [1]:
import tensorflow as tf
import numpy as np
tfs = tf.InteractiveSession()

In [2]:
hello = tf.constant("Hello World!")
print(tfs.run(hello))
print(hello.eval())

b'Hello World!'
b'Hello World!'


#### Interactive vs Session
The only difference between Session() and InteractiveSession() is
that the session created with InteractiveSession() becomes the
default session. Thus, we do not need to specify the session context to
execute the session-related command later. For example, say that we have
a session object, tfs, and a constant object, hello. If tfs is an
InteractiveSession() object, then we can evaluate hello with the
code hello.eval(). If tfs is a Session() object, then we have to
use either tfs.hello.eval() or a with block. The most common
practice is to use the with block, which will be shown later in this chapter.

**Tensors** are the basic elements of computation and a fundamental data structure in TensorFlow.  
A tensor is an n-dimensional collection of data, identified by rank, shape, and type.
Data types can be found [here](https://www.tensorflow.org/api_docs/python/tf/dtypes/DType)

Python objects such as scalar values, lists, and NumPy arrays should be converted to tf data types
using `tf.convert_to_tensor()` function

#### Constants

In [3]:
tf.constant?

Signature:
tf.constant(
    ['value', 'dtype=None', 'shape=None', "name='Const'", 'verify_shape=False'],
)
Docstring:
Creates a constant tensor.

The resulting tensor is populated with values of type `dtype`, as
specified by arguments `value` and (optionally) `shape` (see examples
below).

The argument `value` can be a constant value, or a list of values of type
`dtype`. If `value` is a list, then the length of the list must be less
than or equal to the number of elements implied by the `shape` argument (if
specified). In the case where the list length is less than the number of
elements specified by `shape`, the last element in the list will be used
to fill the remaining entries.

The argument `shape` is optional. If present, it specifies the dimensions of
the resulting tensor. If not present, the shape of `value` is used.

If the argument `dtype` is not specified, then the type is inferred from
the type of `value`.

For example:

```python
# Constant 1-D Tensor populated with value l

In [4]:
x=tf.constant(6, name='x', dtype=tf.float16)
x

<tf.Tensor 'x:0' shape=() dtype=float16>

In [5]:
y=tf.constant(1, name='y', shape=(2,3,), dtype=tf.int8)
y

<tf.Tensor 'y:0' shape=(2, 3) dtype=int8>

In [6]:
# To print the value we need to run the session
tfs.run([x,y])

[6.0, array([[1, 1, 1],
        [1, 1, 1]], dtype=int8)]

#### Operations

In [7]:
# Operations can be applied on tensors
z = tf.constant(5.0, dtype=tf.float16, name='z')
op1 = tf.add(z,x)
op1

<tf.Tensor 'Add:0' shape=() dtype=float16>

In [8]:
tfs.run(op1)

11.0

In [9]:
a = tf.constant([1,2,3])
b = tf.constant([10,20,30])
tfs.run(tf.tensordot(a,b, 0))

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]], dtype=int32)

In [10]:
tfs.run(tf.tensordot(a,b, 1))

140

In [11]:
tf.tensordot?

Signature: tf.tensordot(a, b, axes, name=None)
Docstring:
Tensor contraction of a and b along specified axes.

Tensordot (also known as tensor contraction) sums the product of elements
from `a` and `b` over the indices specified by `a_axes` and `b_axes`.
The lists `a_axes` and `b_axes` specify those pairs of axes along which to
contract the tensors. The axis `a_axes[i]` of `a` must have the same dimension
as axis `b_axes[i]` of `b` for all `i` in `range(0, len(a_axes))`. The lists
`a_axes` and `b_axes` must have identical length and consist of unique
integers that specify valid axes for each of the tensors.

This operation corresponds to `numpy.tensordot(a, b, axes)`.

Example 1: When `a` and `b` are matrices (order 2), the case `axes = 1`
is equivalent to matrix multiplication.

Example 2: When `a` and `b` are matrices (order 2), the case
`axes = [[1], [0]]` is equivalent to matrix multiplication.

Example 3: Suppose that \\(a_{ijk}\\) and \\(b_{lmn}\\) represent two
tensors of order 

*There are a number of operations supported by `tf` please check the book page 14*

#### Placeholders

In [12]:
tf.placeholder?

Signature: tf.placeholder(dtype, shape=None, name=None)
Docstring:
Inserts a placeholder for a tensor that will be always fed.

**Important**: This tensor will produce an error if evaluated. Its value must
be fed using the `feed_dict` optional argument to `Session.run()`,
`Tensor.eval()`, or `Operation.run()`.

For example:

```python
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)

with tf.Session() as sess:
  print(sess.run(y))  # ERROR: will fail because x was not fed.

  rand_array = np.random.rand(1024, 1024)
  print(sess.run(y, feed_dict={x: rand_array}))  # Will succeed.
```

@compatibility(eager)
Placeholders are not compatible with eager execution.
@end_compatibility

Args:
  dtype: The type of elements in the tensor to be fed.
  shape: The shape of the tensor to be fed (optional). If the shape is not
    specified, you can feed a tensor of any shape.
  name: A name for the operation (optional).

Returns:
  A `Tensor` that may be used as a handle for fee

In [13]:
p1 = tf.placeholder(name='p1', dtype=tf.int8)
p2 = tf.placeholder(name='p2', dtype=tf.int8)
print(p1)
print(p2)

Tensor("p1:0", dtype=int8)
Tensor("p2:0", dtype=int8)


In [14]:
tfs.run(p1*p2, feed_dict={p1:2,p2:4})

8

In [15]:
tfs.run(p1*p2, feed_dict={p1:[2,4],p2:[3,6]})

array([ 6, 24], dtype=int8)

**Properties**
- define input data that does not change over time
- no initial value needed

#### Creating tensors from python objects

In [16]:
tf.convert_to_tensor?

Signature: tf.convert_to_tensor(value, dtype=None, name=None, preferred_dtype=None)
Docstring:
Converts the given `value` to a `Tensor`.

This function converts Python objects of various types to `Tensor`
objects. It accepts `Tensor` objects, numpy arrays, Python lists,
and Python scalars. For example:

```python
import numpy as np

def my_func(arg):
  arg = tf.convert_to_tensor(arg, dtype=tf.float32)
  return tf.matmul(arg, arg) + arg

# The following calls are equivalent.
value_1 = my_func(tf.constant([[1.0, 2.0], [3.0, 4.0]]))
value_2 = my_func([[1.0, 2.0], [3.0, 4.0]])
value_3 = my_func(np.array([[1.0, 2.0], [3.0, 4.0]], dtype=np.float32))
```

This function can be useful when composing a new operation in Python
(such as `my_func` in the example above). All standard Python op
constructors apply this function to each of their Tensor-valued
inputs, which allows those ops to accept numpy arrays, Python lists,
and scalars in addition to `Tensor` objects.

Note: This function diverges f

In [17]:
tf.convert_to_tensor(5.0, dtype=tf.float16)

<tf.Tensor 'Const_3:0' shape=() dtype=float16>

In [18]:
tf.convert_to_tensor(np.array([1,2,3,4]), dtype=tf.int8)

<tf.Tensor 'Const_4:0' shape=(4,) dtype=int8>

In [19]:
tf.constant([1,2,3,4], dtype=tf.int8)

<tf.Tensor 'Const_5:0' shape=(4,) dtype=int8>

#### Variables

**Properties**
- Hold values that are modified over time
- Initial value must be provided at definition time

In [20]:
tf.Variable?

Init signature: tf.Variable(*args, **kwargs)
Docstring:     
See the [Variables Guide](https://tensorflow.org/guide/variables).

A variable maintains state in the graph across calls to `run()`. You add a
variable to the graph by constructing an instance of the class `Variable`.

The `Variable()` constructor requires an initial value for the variable,
which can be a `Tensor` of any type and shape. The initial value defines the
type and shape of the variable. After construction, the type and shape of
the variable are fixed. The value can be changed using one of the assign
methods.

If you want to change the shape of a variable later you have to use an
`assign` Op with `validate_shape=False`.

Just like any `Tensor`, variables created with `Variable()` can be used as
inputs for other Ops in the graph. Additionally, all the operators
overloaded for the `Tensor` class are carried over to variables, so you can
also add nodes to the graph by just doing arithmetic on variables.

```python
impo

**Linear Model**
y = W * x + b

In [21]:
w = tf.Variable([.3], dtype=tf.float16, name='W')
b = tf.Variable([.1], dtype=tf.float16, name='b')
x = tf.placeholder(dtype=tf.float16)
y = w * x + b
print(y)
print(w)
print(x)
print(b)

Tensor("add_1:0", dtype=float16)
<tf.Variable 'W:0' shape=(1,) dtype=float16_ref>
Tensor("Placeholder:0", dtype=float16)
<tf.Variable 'b:0' shape=(1,) dtype=float16_ref>


In [22]:
# for initializing only individual variables 
tfs.run(w.initializer)
# for initializing all variables
tf.global_variables_initializer().run()

In [23]:
tfs.run(y, feed_dict={x:3.0})

array([1.], dtype=float16)

### Data flow graph or computational graph (25-33)

### TensorBoard (33-37)